theme: jekyll-theme-slate
title: Codes of Electric Sheep
description: > 
 Random collection of technical posts 

twitter_username: zwhitten
github_username: zwhitten

google_analytics: UA-99634449-1
disqus_shortname: zdub-io

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

gems:
  - jekyll-feed
